### ISSUE TITLE
关于引言部分的显示

### ISSUE THREAD

**Issue by FanBingyang** [zhaoo/hexo-theme-zhaoo#100]
问题：现在情况是引言部分没有被编译，使用&nbsp;会被直接显示出来，而且文章点进去之后引言部分不显示，体验不太好。
期待结果：
1，引言部分在首页也可以被编译。或者为了更美观的展示，在首页看时引言前端空格可以不显示出来，但点进文章时候要展示。例如下面这样：
![image](https://user-images.githubusercontent.com/46048034/142101426-c677a670-e1c2-4b76-b41f-039e99ed19e6.png)
![image](https://user-images.githubusercontent.com/46048034/142103036-5648f055-2e4c-4e9a-b42a-efc524688646.png)
2，在进入文章之后引言也显示在文章中。
3，可以在配置项加一个开关，控制点进文章之后是否直接跳转到引言下面的部分。

顺带提一下目录的展示，能否加个配置项控制目录是在左侧还是在右侧呢？ 这样觉得更灵活一下。

期待尽快解决呀！

**Comment by zhaoo** [comment]
已支持
