### ISSUE TITLE
关于一个文章多个分类时, 分类页面显示不正常

### ISSUE THREAD

**Issue by Deadpoolmine** [zhaoo/hexo-theme-zhaoo#114]
作者你好，首先非常感谢你的模板，设计非常精美。但我发现categories页面显示非常奇怪，如下图所示：
![image](https://user-images.githubusercontent.com/48178553/203902967-670f449c-6769-42ed-8338-1a6222163f06.png)
这里的category-list-item变成嵌套的了，我发现出现这个问题的原因是我一篇文章里出现了两个categories，请问这要怎么修复呢？我不是很了解ejs，但看了一下`categories.ejs`代码，发现有一个`list_categories`，但找不到这个函数的定义，还麻烦作者闲暇时帮忙看看
![image](https://user-images.githubusercontent.com/48178553/203903073-9974e285-bfc6-4e03-906a-a88853c6be9e.png)

**Comment by zhaoo** [comment]
![image](https://user-images.githubusercontent.com/30286980/204205711-5dbd63f1-42d6-4831-9cdf-af6696b0cb70.png)

可能是标签太少了，尝试多写几篇文章和标签样式就比较正常……

**Comment by Deadpoolmine** [comment]
谢谢~
