### ISSUE TITLE
优化的建议

### ISSUE THREAD

**Issue by WinterChenS** [zhaoo/hexo-theme-zhaoo#60]
## web端
- 摄影详情页能否做成方框不拉伸的样式（显示部分），点击才显示原图；
- 关于页增加菜单按钮；
- 文章页希望能增加一个返回按钮。

## 小程序端
- 摄影列表和详情页样式调整为方框不拉伸（显示部分），点击详情才显示原图；
- 摄影列表页增加下拉刷新；

**Comment by izhaoo** [comment]
安排！

**Comment by zhaoo** [comment]
RE:
1. 摄影页现支持 **瀑布流** 形式展示，欢迎使用。
2. 关于页菜单可在 `config.yml` 中配置。
3. 返回按钮现已支持。
