### ISSUE TITLE
正文缩进过多导致目录变为整个页面居中

### ISSUE THREAD

**Issue by so1n** [zhaoo/hexo-theme-zhaoo#69]
![image](https://user-images.githubusercontent.com/28426591/108692526-ad88b200-7537-11eb-8f9f-5ff7fc0381fc.png)

如图, 由于忘记回车, hexo解析时, 变成多层缩进, 这时候目录就变成居中了

**Comment by zhaoo** [comment]
RE：
`hexo` 按照标准 `MarkDown` 规范进行解析，主题只是在此基础上进行样式渲染。建议修改 `MD`，加入回车。
