### ISSUE TITLE
问问一些小bug

### ISSUE THREAD

**Issue by DesnLee** [zhaoo/hexo-theme-zhaoo#71]
- navbar在文章封面图片区域出不来，要拉到内容部分然后才可以显示
- 代码块有的字体很大，有的字体正常（测试发现单行过长会复现）
- 首页background-attachment fixed 在手机的几个浏览器都出现图片被放的特别大，attachment好像不兼容移动端

**未来feature**
- 单行代码块字体颜色和高亮色是否可以加入分别设置
- 搜索模块

**Comment by DesnLee** [comment]
目前我用媒体查询在手机上把attachment属性去掉了，大佬有空研究一下手机上的首屏图片吧

**Comment by zhaoo** [comment]
谢谢，周末修复。

**Comment by zhaoo** [comment]
RE:
1. navbar 图片区不展示：有意为之，聚焦到图片。（可在 JS 源码中控制，有需要可关闭）
2. 代码块字体：正在测试并修复。
3. background-attachment：有意为之，大多情况手机端需要对图片进行一个等比裁剪，否则图片比例会失调。（有需要可关闭）
4. 代码块颜色：采用 `highlight.js` 预置配置项，不再进行单独配置。
5. 搜索模块： 正在开发。
