### ISSUE TITLE
ux: 键盘 esc 关闭 menu & search 后，nav 没有显示

### ISSUE THREAD

**Issue by hcanyz** [zhaoo/hexo-theme-zhaoo#82]
https://github.com/zhaoo/hexo-theme-zhaoo/blob/7c853d98b060eb55a8027eed6a2c913de0ca70a0/source/js/script.js#L12
https://github.com/zhaoo/hexo-theme-zhaoo/blob/7c853d98b060eb55a8027eed6a2c913de0ca70a0/source/js/script.js#L24

没有将 nav 复原显示。

**Comment by zhaoo** [comment]
稍后修复一下。其实页面滚一下就出来了（逃...）

**Comment by zhaoo** [comment]
已修复。

**Comment by hcanyz** [comment]
https://github.com/zhaoo/hexo-theme-zhaoo/blob/7c853d98b060eb55a8027eed6a2c913de0ca70a0/source/js/script.js#L24

🤣🤣🤣

**Comment by zhaoo** [comment]
叕修复了。
