### ISSUE TITLE
底部微信链接似乎不可用

### ISSUE THREAD

**Issue by JasonLamv-t** [zhaoo/hexo-theme-zhaoo#88]
如题，或者我太菜了

**Comment by zhaoo** [comment]
这个还没开发，本来想做个二维码。

**Comment by JasonLamv-t** [comment]
你好，你的博客访问好像失效了

2021年6月16日 下午12:49，兆兆 ***@***.******@***.***>> 写道：



这个还没开发，本来想做个二维码。

**Comment by zhaoo** [comment]
刚发现了，似乎是七牛炸了，正在排查，谢谢！

**Comment by JasonLamv-t** [comment]
想起来，我在使用的时候发现我的字数统计不准确，但是我看你的博客的字数统计好像是准确的，我自己换了wordcount，并修改了layout中对于样式的定义后准确了。
zhaoo/layout/_partial/post/head.ejs:

<span class="post-info-item"><i class="iconfont iconfont-size"></i><%= wordcount(page.content) %></span>

首页的layout也需要进行修改

2021年6月16日 下午12:52，兆兆 ***@***.******@***.***>> 写道：



刚发现了，似乎是七牛炸了，正在排查，谢谢！
