### ISSUE TITLE
如何自定义文章的摘要以及折叠阅读？

### ISSUE THREAD

**Issue by frankwuzp** [zhaoo/hexo-theme-zhaoo#93]
## 问题描述
搭建了hexo博客，安装好zhaoo主题后，发现两个问题，网上找了很久，没解决：
1. 博客正文自动生成了前三行为摘要，但我想自己定义文章的摘要，30-50字即可
2. 在博客文章内插入一行代码`<!--more-->`，本意是为了实现折叠阅读，结果是代码前面的部分被折叠了，尬...

 ## 诉求
想知道这两个问题的解决办法

## 已经尝试
1. 在文章的`Front-matter`中添加了`description`字段，结果无效
2. 在主题的'_config.yml'中加入'auto_excerpt'，同时设置值为'false'，结果无效
3. 折叠阅读的功能是真的不知要怎么实现了

## Changelog
- 210720，提交issue

**Comment by zhaoo** [comment]
我目前是将  前面部分作为摘要使用的，后面部分才是正文。可能他的本意如你所说是折叠的功能，那么我误解了，并没有开发这个能力。待我了解后再作更新，修复这个尴尬的问题。
