### ISSUE TITLE
代码高亮主题在变更后，高亮加载css的cdn报404

### ISSUE THREAD

**Issue by ITt-mac** [zhaoo/hexo-theme-zhaoo#95]
![image](https://user-images.githubusercontent.com/29789346/129830161-6da5ce50-c5af-479d-a0c5-ff83d217d69c.png)

**Comment by ITt-mac** [comment]
![image](https://user-images.githubusercontent.com/29789346/129830380-b2062983-abc3-46e6-b11c-a160356eef76.png)

在cdn设置highlight_css的高亮的版本路径更新为highlight.js最近发行的几个版本号。

**Comment by zhaoo** [comment]
手动替换一下 `CDN` 即可
