### ISSUE TITLE
日期格式

### ISSUE THREAD

**Issue by jaywangcc** [zhaoo/hexo-theme-zhaoo#99]
文章左下角的日期格式怎么自定义啊，样式类名post-info-item，我看你的月份显示的是中文，但自己的却显示的是英文？？？

**Comment by zhaoo** [comment]
`config.yml` 配置文件里面把 `language` 语言改成 `zh_CN` 中文。

**Comment by jaywangcc** [comment]
> `config.yml` 配置文件里面把 `language` 语言改成 `zh_CN` 中文。

感谢，已经解决了😊
